#!/usr/bin/env bash
set -euxo pipefail
ACMEAPI="$GOPATH/src/gopkg.in/hlandau/acmeapi.v2"

go get ./... github.com/letsencrypt/pebble/cmd/pebble
go install ./... github.com/letsencrypt/pebble/cmd/pebble

"$ACMEAPI/.drone/with-pebble" go test -tags integration ./...
